$(function(){function B(){2==r?p(1):p(2)}function C(){t=mou.window.width();x=mou.window.height();g.resize(t,x);y=x<t;D()}function D(){u&&(1!=h?($("#bt_back").stop().fadeIn(100,"linear"),z&&$("#bt_fs").stop().fadeIn(100,"linear")):y?($("#bt_back").stop().fadeOut(100,"linear"),z&&$("#bt_fs").stop().fadeOut(100,"linear")):($("#bt_back").stop().fadeIn(100,"linear"),z&&$("#bt_fs").stop().fadeIn(100,"linear")))}function M(){g.start();C();0>=h&&$("#cover").animate({opacity:.5},300,"linear")}function p(l){r=
l;g.changeMode(l);$("#mode"+l).css({opacity:1,cursor:"default"});var b=1;1==l&&(b=2);$("#mode"+b).css({opacity:.3,cursor:"pointer"});mou.util.setCookie("mode",l,2592E3)}function H(){$.ajax({url:"data/data.json",dataType:"json",success:function(b){g.setTexts(b.list);$("#scene1").fadeIn(300,"linear")}})}function I(){u&&1==m.type&&(f=setTimeout(function(){$.ajax({type:"POST",url:"",data:{log:navigator.userAgent},success:function(b){mou.util.setCookie("wa","no",2592E3)}})},1E4))}
function J(){clearTimeout(f);q=!0;$("#cover").stop().animate({opacity:0},300,"linear",function(){$("#cover").css("display","none")});h=1;g.change(h);D();$("#scene_progress").stop().fadeOut(100,"linear")}var E=mou.util.checkJapanese(),u=mou.util.checkMobile();mou.util.useDummyDiv();mou.util.needExpandArea(!0);var z=mou.util.enabledFullscreen();z&&($("#bt_fs").css("display","block"),$("#bt_fs").click(function(b){mou.util.fullscreen()}));$("#bt_start").click(function(){$("#scene1").stop().fadeOut(100,
"linear");$("#scene_progress").stop().delay(100).fadeIn(100,"linear");q||m.load(A,I);m.play(0,!0,J,O,P);if(1==b){for(var l=[],h=0;5>h;h++){var f=new mou.Audio;f.load(["../../shared/sound/blank.mp3"]);l[h]=f}g.setupNormalAudio(l)}});$("#bt_about").click(function(){$("#about").stop().fadeIn(200,"linear");$("#about_cover").stop().fadeIn(200,"linear")});$("#bt_close,#about_cover").click(function(){$("#about").stop().fadeOut(200,"linear");$("#about_cover").stop().fadeOut(200,"linear")});$("#bt_back").click(function(){switch(h){case 1:h=
0;g.change(h);D();$("#cover").stop().css("display","block").animate({opacity:.5},300,"linear");m.stop();$("#scene1").stop().fadeIn(100,"linear");$("#scene_progress").stop().fadeOut(0);break;default:location.href=""}});var O=2.5,P=1,A=["data/sound.swf","data/sound.mp3"],y=!1,t,x,h=-1,q=!1,f=-1,r;$("#tw").click(function(b){mou.social.shareTw("",!0,document.title,"daniwell_mou")});$("#fb").click(function(b){mou.social.shareFb("",!0)});
$("#gp").click(function(b){mou.social.shareGp("",!0)});var b=0;mou.util.webgl&&mou.util.webaudio&&(b=2);"no"==mou.util.getCookie("wa")&&(b=0);0==b&&mou.util.webgl&&(!u||mou.util.checkAndroid()&&mou.util.checkChrome())&&(b=1);E||$("#about_in .link a").attr("href","");if(0==b)$("#ng").css("display","block"),$(".ok").css("display","none"),E||$("#ng .atten").html("your device or browser doesn't support this site."),
$("#scene1").fadeIn(300,"linear");else{$("#ng").css("display","none");E?($("#at_sound").text(""),u?$("#at_ope").text(""):$("#at_ope").text("")):($(".album a").attr("href",""),$("#at_sound").text(""),
u?$("#at_ope").text("* Please operate by tilting the smartphone."):$("#at_ope").text("* Please operate by moving the mouse."));var g=new ThreeController;g.init(M);$("#mode1").click(B);$("#mode2").click(B);0<mou.util.getCookie("mode")?p(mou.util.getCookie("mode")):p(1);mou.window.resize(C);var m=m=new mou.AutoAudio("../shared/swf/audio.swf",H)}u||$("#pc").css("display","block")});
var ThreeController=function(){function B(a){0<=a||(a=0);a=2*a+Math.round(Math.random());if(!I){I=!0;for(var k="rgb(  0, 204, 255);rgb(  0, 204, 204);rgb(255, 153, 204);rgb(255, 153, 153);rgb(255, 204,   0);rgb(255, 153,   0)".split(";"),c=0;c<k.length;c++){var d=c,n=k[c],e=document.createElement("canvas");e.width=32;e.height=32;var b=e.getContext("2d");b.fillStyle=n;b.beginPath();b.arc(16,16,16,0,2*Math.PI,!0);b.fill();n=new THREE.Texture(e);n.needsUpdate=!0;n=new THREE.MeshBasicMaterial({map:n});
H[d]=n}}return H[a]}function C(){var a=mou.util.getTime(),k=a-N;N=a;x?l.update():m.update(k);Q.update(k);0<K&&(F.update(k),A+=k,50<A&&(a=new THREE.Vector3(0,0,1),t.setFromCamera(a,b),F.hitCheck(t),A=0));J?r.render(g,b):f.render(g,b);window.requestAnimFrame(C)}this.MODE_TOP=0;this.MODE_MAIN=1;this.resize=function(a,k){h=a;q=k;f&&(r.setSize(h,q),b.aspect=h/q,b.updateProjectionMatrix())};this.change=function(a){K!=a&&(K=a,F.change(K))};this.setTexts=function(a){S=a;G=a.length;for(a=0;a<G;a++)w[a]=a;
for(a=0;a<G;a++){var k=w[a],c=Math.floor(Math.random()*G);w[a]=w[c];w[c]=k}F=new O;F.init()};this.init=function(a){y=a;f=new THREE.WebGLRenderer({antialias:!1,alpha:!0});f.setClearColor(0);a=1;1<window.devicePixelRatio&&(a=2);f.setPixelRatio(a);$("#view").html(f.domElement);r=new THREE.StereoEffect(f);b=new THREE.PerspectiveCamera(100,h/q);b.position.set(0,0,1);g=new THREE.Scene;g.add(b);Q=new M;Q.init();x?(l=new THREE.DeviceOrientationControls(b),l.speed=0,b.position.z=0):(m=new THREE.OrbitControls(b),
m.minPolarAngle=.2*Math.PI,m.maxPolarAngle=.8*Math.PI);y&&y()};this.start=function(){N=mou.util.getTime();C()};this.changeMode=function(a){J=2==a;P.resize(h,q)};this.setupNormalAudio=function(a){R=a};var D=function(a){this.update=function(a){c.position.y+=.1*a;.3>Math.random()&&(c.visible=!c.visible);d<c.position.y&&(c.position.y-=2*d)};this.init=function(a){var e=2*d;c=new THREE.Sprite(a);c.position.x=Math.random()*e-d;c.position.y=Math.random()*e-d;c.position.z=Math.random()*e-d;c.scale.x=c.scale.y=
6*Math.random()+3;k.add(c)};var k=a,c,d=1500},M=function(){this.update=function(c){for(var d=0;d<k;d++)a[d].update(c)};this.init=function(){var c=THREE.Texture,d=document.createElement("canvas");d.width=16;d.height=16;var b=d.getContext("2d");b.fillStyle="rgb(255, 255, 255)";b.beginPath();b.arc(8,8,8,0,2*Math.PI,!0);b.fill();c=new c(d);c.needsUpdate=!0;c=new THREE.SpriteMaterial({map:c});c.opacity=.7;for(d=0;d<k;d++)b=new D(g),b.init(c),a[d]=b};var a=[],k=500},p,H=[],I=!1,J=!1,E=function(a){this.update=
function(a){if(!b)return!1;.2>Math.random()&&(e.visible=!e.visible);return!0};this.start=function(){b=!0;e.visible=!0;var a=Math.random()-.5+1;TweenLite.to(e.scale,1,{x:a,y:a,ease:Elastic.easeOut,onComplete:function(){var a=e.position.x+80*Math.random()-40,c=e.position.y+80*Math.random()-40;TweenLite.to(e.position,1,{x:a,y:c,ease:Power3.easeOut,onComplete:function(){b=!1;e.visible=!1}});TweenLite.to(e.scale,1,{x:1E-4,y:1E-4,ease:Power3.easeOut})}});TweenLite.to(e.position,1,{z:Math.random(),ease:Elastic.easeOut})};
this.init=function(a,d,b,k,n){e.position.x=(a-.5*b)*c*1.3;e.position.y=-(d-.5*k)*c*1.3;e.material=B(n);e.visible=!1;e.scale.set(1E-4,1E-4,1);e.position.z=60*Math.random()-30};var b=!1,c=3,d;p||(p=new THREE.PlaneGeometry(c,c,1,1));d=p;var n=B(),e=new THREE.Mesh(d,n);a.add(e)},u=function(a){this.update=function(a){if(p){b.rotation.x+=a*g;b.rotation.y+=a*f;for(var h=n!=e,v=0;v<n;v++)c[v].update(a)&&(h=!0);if(!h)for(p=!1,v=0;v<e;v++)d.push(c.pop());if(m){for(a=Math.min(Math.floor(.5*a)+n,e);n<a;n++)c[n].start();
e<=n&&(m=!1)}}};this.setText=function(a){l=a;a=l.length;for(var h=l[0].length,v=Math.floor(3*Math.random()),g=0;g<h;g++)for(var f=0;f<a;f++)if(0<l[f][g]){var m;m=0<d.length?d.pop():new E(b);m.init(g,f,h,a,v);c.push(m)}n=0;e=c.length};this.start=function(){p=m=!0;g=1.5E-4+2E-4*Math.random();f=1.5E-4+2E-4*Math.random();.5>Math.random()&&(g=-g);.5>Math.random()&&(f=-f);b.rotation.x=0;b.rotation.y=h};this.init=function(a){h=b.rotation.y=a};var b=new THREE.Group;a.add(b);var c=[],d=[],n=0,e=0,h,g=0,f=
0,l,m=!1,p=!1},z=function(a){function b(){m=L;var a="data/voice/"+w[0]+".mp3";R&&(r=R[h]);r.load([a],c);p.setText(S[w[m]]);d.position.y=120*Math.random()-60;a=100-40*Math.random();d.position.x=-Math.sin(q)*a;d.position.z=-Math.cos(q)*a;L++;G<=L&&(L=0)}function c(){l=!0;e.visible=!0}this.hitCheck=function(a){l&&0<a.intersectObject(g).length&&(l=e.visible=!1,r.play(),p.start(),setTimeout(b,5E3))};this.change=function(a){switch(a){case 0:d.visible=!1;break;case 1:d.visible=!0,t&&(t=!1,b())}};this.update=
function(a){e.rotation.x+=a/800;e.rotation.z+=a/900;f+=a;60<f&&(g.visible=!g.visible,f=0);p.update(a)};this.init=function(a,b){h=a;var c=new THREE.BoxGeometry(5,5,5),f=new THREE.MeshBasicMaterial({color:"#ffffff"}),f=new THREE.Mesh(c,f),k=new THREE.MeshBasicMaterial({color:"#ffffff",transparent:!0,opacity:.1}),c=new THREE.Mesh(c,k);c.scale.set(8,8,8);f.add(c);k=360/b*a*Math.PI/180;f.rotation.x=Math.random();f.rotation.z=Math.random();p=new u(d);p.init(k);f.visible=l;q=k;d.add(f);e=f;g=c};var d=new THREE.Group;
d.visible=!1;a.add(d);var h,e,g,f=0,m=0,l=!1,p,q,r=new mou.WebAudio,t=!0},O=function(){this.hitCheck=function(c){for(var d=0;d<b;d++)a[d].hitCheck(c)};this.change=function(c){for(var d=0;d<b;d++)a[d].change(c)};this.update=function(c){for(var d=0;d<b;d++)a[d].update(c)};this.init=function(){for(var c=0;c<b;c++){var d=new z(g);d.init(c,b);a[c]=d}};var a=[],b=5},P=this,A=0,y,t=new THREE.Raycaster,x=mou.util.checkMobile(),h=mou.window.width(),q=mou.window.height(),f,r,b,g,m,l,N,K=-1,S,w=[],G=0,L=
0,R=null,Q,F};
